[theme]
# base = "dark"
primaryColor = "#DC4bFF"
# primaryColor = "#F63366"
backgroundColor = "#FAF7F8"
# backgroundColor = "#293745"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#white"
font = "Serif, Sans-Serif, Monospace"
# font = "Sans-Serif, Monospace"

[server]
runOnSave = true

[runner]
fastReruns = true

[browser]
gatherUsageStats = false